title: Cloud Federation using Resource Sharing Contracts
description: 
baseurl: "/ContractsCloud" 
url: "https://bpln.github.io/ContractsCloud"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal