title: PADS
description: Privacy-preserving Auction Design for Allocating Dynamically Priced Cloud Resources
baseurl: "/PADS" 
url: "https://bpln.github.io/PADS"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal