title: PADS
description: Privacy-preserving Auction Design for Allocating Dynamically Priced Cloud Resources
baseurl: "/PADS" 
url: "https://bpln.github.io/PADS"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class